site_name: atoutprises
site_description: Wall viewer and leaderboard
repo_url: https://github.com/jonasrenault/atoutprises
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/jonasrenault">jonasrenault</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
