# Generated by Django 2.0.7 on 2018-07-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setter', models.CharField(max_length=256)),
                ('colour', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('lane', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('max_zoom', models.IntegerField(null=True)),
                ('tiles_per_zoom', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voies.Wall'),
        ),
    ]
