# Generated by Django 2.0.7 on 2018-07-31 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setter', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('lane', models.CharField(max_length=100)),
                ('holds', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topped', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppers', to='voies.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('max_zoom', models.IntegerField(null=True)),
                ('tiles_per_zoom', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='voies.Wall'),
        ),
        migrations.AlterUniqueTogether(
            name='top',
            unique_together={('climber', 'route')},
        ),
    ]
