# Generated by Django 2.0.7 on 2018-07-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='holds',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='voies.Wall'),
        ),
    ]
