# Generated by Django 2.0.7 on 2018-07-30 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voies', '0003_auto_20180730_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='climber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topped', to=settings.AUTH_USER_MODEL),
        ),
    ]
